bmarket/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bmarket import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('cart/', include('carts.urls', namespace="cart")),
    path('', include('books.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Магазин книг'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.BooksHome.as_view(), name='home'),
    path('catalog/', views.Catalog.as_view(), name='catalog'),
    path('item/<slug:item_slug>/', views.ShowItem.as_view(), name='item'),
    path('catalog/author/<slug:author_slug>/', views.BooksFilterByAuthor.as_view(), name='author'),
    path('catalog/search/', views.Search.as_view(), name='search'),
]

carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('details', views.get_user_cart, name='details'),
    path('cart_add/<slug:item_slug>', views.cart_add, name='cart_add'),
    path('add_cart_item/<int:cart_id>', views.add_cart_item, name='add_cart_item'),
    path('reduce_cart_item/<int:cart_id>', views.reduce_cart_item, name='reduce_cart_item'),
    path('cart_remove/<int:cart_id>', views.cart_remove, name='cart_remove'),
    path('create_order/', views.create_order, name='create_order'),
]

carts/models.py
from django.db import models

from books.models import Books
from users.models import User


class CartQueryset(models.QuerySet):

    def total_price(self):
        return sum(cart.item_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Cart(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Пользователь')
    item = models.ForeignKey(to=Books, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')
    session_key = models.CharField(max_length=32, null=True, blank=True)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')

    class Meta:
        db_table = 'carts'
        verbose_name = "Корзина"
        verbose_name_plural = "Корзины"

    objects = CartQueryset().as_manager()

    def __str__(self):
        if self.user:
            return f'Корзина {self.user.username} | Товар {self.item.title} | Количество {self.quantity}'

        return f'Анонимная корзина | Товар {self.item.title} | Количество {self.quantity}'

    def item_price(self):
        return self.item.price * self.quantity

carts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import render, redirect
from django.forms import ValidationError

from books.models import Books
from carts.models import Cart
from users.models import User


def get_user_cart(request):
    return render(request, 'cart/details.html')


def cart_add(request, item_slug):
    item = Books.objects.get(slug=item_slug)

    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, item=item)

        if carts.exists():
            carts = carts.first()
            carts.quantity += 1
            carts.save()
        else:
            Cart.objects.create(user=request.user, item=item, quantity=1)

    else:
        carts = Cart.objects.filter(session_key=request.session.session_key, item=item)

        if carts.exists():
            cart = carts.first()
            cart.quantity += 1
            cart.save()
        else:
            Cart.objects.create(session_key=request.session.session_key, item=item, quantity=1)

    return redirect(request.META.get('HTTP_REFERER'))


def add_cart_item(request, cart_id):
    cart = Cart.objects.get(id=cart_id)
    cart.quantity += 1
    cart.save()

    return redirect(request.META.get('HTTP_REFERER'))


def reduce_cart_item(request, cart_id):
    cart = Cart.objects.get(id=cart_id)
    cart.quantity -= 1
    cart.save()

    return redirect(request.META.get('HTTP_REFERER'))


def cart_remove(request, cart_id):
    cart = Cart.objects.get(id=cart_id)
    cart.delete()
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def create_order(request):
    if request.method == 'POST':
        try:
            with transaction.atomic():
                user = request.user
                cart_items = Cart.objects.filter(user=user)

                if cart_items.exists():

                    total_cart_price = 0
                    for cart_item in cart_items:
                        if cart_item.item.amount < cart_item.quantity:
                            raise ValidationError(f'Недостаточное количество товара "{cart_item.item.title}",\
                                                   в наличии - {cart_item.item.amount}.')

                        if user.purse < cart_item.item.price:
                            raise ValidationError(f'Недостаточное монет в кошельке для оплаты товара '
                                                  f'"{cart_item.item.title}", баланс - {user.purse} У.Е.')

                        book_remains = cart_item.item.amount - cart_item.quantity
                        Books.objects.filter(title=cart_item.item.title).update(amount=book_remains)

                        total_cart_price += cart_item.item_price()

                    if user.purse < total_cart_price:
                        raise ValidationError(f'Недостаточное монет в кошельке для оплаты товаров на сумму '
                                              f'{total_cart_price} У.Е., баланс - {user.purse} У.Е.')

                    purse_remains = user.purse - total_cart_price
                    User.objects.filter(username=user.username).update(purse=purse_remains)

                    cart_items.delete()

                    return render(request, 'cart/order_done.html')

        except ValidationError as error:
            messages.info(request, list(error)[0])
            return render(request, 'cart/validation_error.html')

    return redirect('home')

carts/templates/cart/details.html
{% extends 'base.html' %}
{% load carts_tags %}

{% block content %}

{% user_carts request as carts %}
<div class="cart">
<h1>Корзина</h1>
{% for cart in carts %}
    <h4>{{ cart.item.title }}</h4>
    <ul>
        <li>
            <div>
                {% if cart.quantity > 1 %}
                    <form action="{% url 'cart:reduce_cart_item' cart.id %}" class="cart_button_form">
                        <button type="submit">-</button>
                    </form>
                {% endif %}
                    {{ cart.quantity }}
                <form action="{% url 'cart:add_cart_item' cart.id %}" class="cart_button_form">
                <button type="submit">+</button>
                </form>
                x {{ cart.item.price }} =
                {{cart.item_price}} У.Е.
                <a href="{% url 'cart:cart_remove' cart.id %}" class="cart_delete">Удалить</a>
            </div>
        </li>
    </ul>
{% endfor %}

Итого <strong>{{ carts.total_quantity }}</strong> ед. товар(а) на сумму <strong>{{ carts.total_price }} У.Е.</strong>

{% if carts %}
<form action="{% url 'cart:create_order' %}" class="cart_confirm" method="post">
    {% csrf_token %}
    <button class="cart_confirm" >Оформить заказ</button>
</form>
</div>
{% endif %}

{% endblock %}

carts/templates/cart/order_done.html
{% extends 'base.html' %}

{% block content %}
<div class="order_complete">
<h1>Заказ успешно оформлен.</h1>
</div>
{% endblock %}

carts/templates/cart/validation_error.html
{% extends 'base.html' %}

{% block content %}
<div class="validation_error">
{% for message in messages %}
    <h3>{{ message }}</h3>
{% endfor %}
</div>
{% endblock %}