bmarket/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bmarket import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('cart/', include('carts.urls', namespace="cart")),
    path('', include('books.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Магазин книг'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.BooksHome.as_view(), name='home'),
    path('catalog/', views.Catalog.as_view(), name='catalog'),
    path('item/<slug:item_slug>/', views.ShowItem.as_view(), name='item'),
    path('catalog/author/<slug:author_slug>/', views.BooksFilterByAuthor.as_view(), name='author'),
    path('catalog/search/', views.Search.as_view(), name='search'),
]

carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('details', views.get_user_cart, name='details'),
    path('cart_add/<slug:item_slug>', views.cart_add, name='cart_add'),
    path('add_cart_item/<int:cart_id>', views.add_cart_item, name='add_cart_item'),
    path('reduce_cart_item/<int:cart_id>', views.reduce_cart_item, name='reduce_cart_item'),
    path('cart_remove/<int:cart_id>', views.cart_remove, name='cart_remove'),
    path('create_order/', views.create_order, name='create_order'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),

    path('password-reset/', PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done")), name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete")), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"), name='password_reset_complete'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {{ title }} </title>
    <link type="text/css" href="{% static 'books/css/styles.css' %}" rel="stylesheet">
</head>
<body>
<table class="mainmenu_table">
    <tr><td>
            <ul class="mainmenu">
                {% for m in mainmenu %}
                    {% if forloop.counter0 < 2 %}
                        <li class="links_left"><a href="{% url m.url_name %}">{{ m.title }}</a></li>
                    {% else %}
                        <li class="links_right"><a href="{% url 'cart:details' %}">{{ m.title }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if user.is_authenticated %}
                    <form action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <li class="links_right"><a href="{% url 'users:profile' %}">{{user.username}}</a> |
                            <button type="submit">Выйти</button></li>
                    </form>
                {% else %}
                    <li class="links_right"><a href="{% url 'users:login' %}">Войти</a> |
                        <a href="{% url 'users:register' %}">Регистрация</a></li>
                {% endif %}
                <li>
                <form class="search_field" action="{% url 'search' %}" method="get" >
                    <input type="search" name="q" placeholder="Поиск по сайту">
                    <button type="submit">Поиск</button>
                </form>
                </li>
            </ul>
    </td></tr>
</table>
{% block sidemenu %}
{% endblock %}
{% block content %}
{% endblock %}
{% block navigation %}
{% endblock %}
<table class="footer_table">
    <tr><td>
        <div class="footer_text">Сайт создан в учебных целях</div>
    </td></tr>
</table>
</body>
</html>