bmarket/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bmarket import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('cart/', include('carts.urls', namespace="cart")),
    path('', include('books.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Магазин книг'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.BooksHome.as_view(), name='home'),
    path('catalog/', views.Catalog.as_view(), name='catalog'),
    path('item/<slug:item_slug>/', views.ShowItem.as_view(), name='item'),
    path('catalog/author/<slug:author_slug>/', views.BooksFilterByAuthor.as_view(), name='author'),
    path('catalog/search/', views.Search.as_view(), name='search'),
]

carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('details', views.get_user_cart, name='details'),
    path('cart_add/<slug:item_slug>', views.cart_add, name='cart_add'),
    path('add_cart_item/<int:cart_id>', views.add_cart_item, name='add_cart_item'),
    path('reduce_cart_item/<int:cart_id>', views.reduce_cart_item, name='reduce_cart_item'),
    path('cart_remove/<int:cart_id>', views.cart_remove, name='cart_remove'),
    path('create_order/', views.create_order, name='create_order'),
]

books/models.py
from django.db import models
from django.urls import reverse
from django_extensions.db.fields import AutoSlugField
from slugify import slugify


class Books(models.Model):
    title = models.CharField(max_length=100, verbose_name='Наименование')
    slug = AutoSlugField(populate_from='title', slugify_function=slugify, max_length=100, verbose_name='Slug')
    description = models.TextField(blank=True, verbose_name='Описание')
    image = models.ImageField(blank=True, null=True, default=None, verbose_name='Изображение')
    amount = models.IntegerField(default=10, verbose_name='Количество')
    price = models.IntegerField(default=0, verbose_name='Цена')
    author = models.ForeignKey('Authors', on_delete=models.PROTECT, related_name='book', null=True)

    objects = models.Manager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Книги'
        verbose_name_plural = 'Книги'
        indexes = [
            models.Index(fields=['slug'])
        ]

    def get_absolute_url(self):
        return reverse('item', kwargs={'item_slug': self.slug})


class Authors(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    middle_name = models.CharField(max_length=100, verbose_name='Отчество/Второе имя')
    last_name = models.CharField(max_length=100, blank=True, verbose_name='Фамилия')
    slug = AutoSlugField(populate_from='last_name', slugify_function=slugify, max_length=100)

    def __str__(self):
        return self.last_name

    def get_absolute_url(self):
        return reverse('author', kwargs={'author_slug': self.slug})

books/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.views.generic import ListView, DetailView

from .models import Books
from .utils import DataMixin


class BooksHome(DataMixin, ListView):
    model = Books
    template_name = 'books/index.html'
    context_object_name = 'items'
    title_page = 'Главная страница'


class Catalog(DataMixin, ListView):
    model = Books
    template_name = 'books/catalog.html'
    context_object_name = 'items'
    title_page = 'Каталог'

    def get_ordering(self):
        ordering = self.request.GET.get('order_by', None)
        return ordering


class Search(DataMixin, ListView):
    model = Books
    context_object_name = 'items'
    template_name = 'books/catalog.html'
    title_page = 'Поиск'

    def get_queryset(self):
        ordering = self.request.GET.get('order_by', None)
        result = Books.objects.filter(Q(title__icontains=self.request.GET.get('q')) |
                                      Q(author__last_name__icontains=self.request.GET.get('q')))
        if ordering:
            return result.order_by(ordering)
        return result


class ShowItem(DataMixin, DetailView):
    model = Books
    template_name = 'books/item.html'
    slug_url_kwarg = 'item_slug'
    context_object_name = 'item'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context, title=context['item'].title)


class BooksFilterByAuthor(DataMixin, ListView):
    template_name = 'books/catalog.html'
    context_object_name = 'items'

    def get_queryset(self):
        ordering = self.request.GET.get('order_by', None)
        result = Books.objects.filter(author__slug=self.kwargs['author_slug']).select_related('author')

        if ordering:
            return result.order_by(ordering)
        return result

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        author = context['items'][0].author
        return self.get_mixin_context(context, title='Автор - ' + author.last_name)

books/templates/books/catalog.html
{% extends 'base.html' %}

{% load books_tags %}

{% block sidemenu %}

<table class="sidemenu">
    <tr><td class="sidemenu_title">ФИЛЬТРЫ</td></tr>
    <tr><td class="sidemenu_sub_title">Авторы</td></tr>
    <tr><td>{% show_authors %}</td></tr>
    <tr><td class="sidemenu_title">СОРТИРОВКА</td></tr>
    <tr><td><select class="custom_select" onchange="location = this.value" autofocus>
        {% if request.GET.q %}
            <option selected disabled=""></option>
            <option value="?q={{ request.GET.q }}&order_by">По умолчанию</option>
            <option value="?q={{ request.GET.q }}&order_by=price">От дешевых к дорогим</option>
            <option value="?q={{ request.GET.q }}&order_by=-price">От дорогих к дешевым</option>
        {% else %}
            <option selected disabled=""></option>
            <option value="?order_by">По умолчанию</option>
            <option value="?order_by=price">От дешевых к дорогим</option>
            <option value="?order_by=-price">От дорогих к дешевым</option>
        {% endif %}
        </select>
    </td></tr>
</table>

{% endblock %}

{% block content %}

{% include 'books/includes/books_table.html' %}

{% endblock %}

books/templates/books/index.html
{% extends 'base.html' %}

{% load cache %}

{% block content %}

{% cache 30 index %}
{% include 'books/includes/books_table.html' %}
{% endcache %}

{% endblock %}

books/templates/books/item.html
{% extends 'base.html' %}

{% block content %}

<div class="item">
{% if item.image %}
    <p><img class='item_image' src="{{ item.image.url }}"></p>
{% endif %}
<h1>{{ item.title }}</h1>
<h2>{{ item.author.name.0 }}. {{ item.author.middle_name.0 }}. {{ item.author.last_name }}</h2>
<h2>{{ item.description }}</h2>
<form action="{% url 'cart:cart_add' item.slug %}"><button type="submit" class="item_button">Добавить в корзину</button></form>
</div>

{% endblock %}

books/templates/books/list_of_authors.html
<select class="custom_select" onchange="location = this.value">
<option selected disabled>Выбрать автора</option>
<option value="{% url 'catalog' %}">Все авторы</option>
{% for author in authors %}
    <option value="{{ author.get_absolute_url }}">{{ author.last_name }}</option>
{% endfor %}
</select>